### ISSUE TITLE
Electron driver does not work

### ISSUE THREAD

**Issue by Squiccups** [robertgates55/frameworkium-core#23]
Trying to run an automated test using electron fails. Trying to run a test comes up with this:

org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

**Comment by jleeh** [comment]
This was a difficult one as there was a lack of documentation to implement in Java, as it was primarily JavaScript. I'll be able to look into this later this week, or at the start of next. In the meantime, can you use the pages before they're compiled into electron?

**Comment by Squiccups** [comment]
I've created a fix locally, I'm just waiting for Rob to mark me as a collaborator so that I can create a branch to fix this issue

**Comment by robertgates55** [comment]
You should now be a collaborator

**Comment by jleeh** [comment]
Closing this as it's resolved.
