### ISSUE TITLE
Do not open the allure reports In Chrome.

### ISSUE THREAD

**Issue by SuitGuy** [robertgates55/frameworkium-core#5]
The reports are fine but do not work in in chrome. this is a known allure issue but is worth adding to the wiki.

https://github.com/allure-framework/allure-cli/issues/21

**Comment by robertgates55** [comment]
Yep - opening directly in chrome from a filepath will error.

If running via the jenkins plugin, though - worth knowing the reports open just fine.

**Comment by jleeh** [comment]
Allure's response is to not use Chrome, rather a different browser. Closing this issue due to 3rd party plugin issue.
