### ISSUE TITLE
Cannot use 'driver' in components

### ISSUE THREAD

**Issue by robertgates55** [robertgates55/frameworkium-core#6]
Currently cannot use the injected 'driver' in the components - meaning for shared menus that require hovering we cannot use the 'moveToElement' type methods.

Either need to find a way to have this injected here too, or need to give an example where we can use it (a getDriver() call, for example?)

**Comment by robertgates55** [comment]
This can be achieved with BaseTest.getDriver() - is this threadsafe or do we need to get the wrapped driver?

**Comment by ham1** [comment]
Should be threadsafe as it's accessing the ThreadLocal field.

**Comment by robertgates55** [comment]
Going to close this, but first want to add an example into one of component examples (github) that involves a hover

**Comment by jleeh** [comment]
Closing as per Rob's comment.
